version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bit68-task
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mina
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  # flake8:
  #   image: hoto/flake8:latest
  #   build: .
  #   command: flake8 --version